# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{blinksale}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tomasz Werbicki"]
  s.date = %q{2011-06-28}
  s.description = %q{Basic Blinksale invoice fetcher.}
  s.email = %q{tomasz@werbicki.net}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "blinksale.gemspec",
    "lib/blinksale.rb",
    "lib/clients.rb",
    "lib/invoices.rb",
    "spec/blinksale_spec.rb",
    "spec/fixtures/invoice_collection.xml",
    "spec/fixtures/invoice_single.xml",
    "spec/invoice_spec.rb",
    "spec/invoices_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/neaf/blinksale}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Basic Blinksale invoice fetcher.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.6.3"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.4.6"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<mocha>, ["~> 0.9.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.4.2"])
    else
      s.add_dependency(%q<rest-client>, ["~> 1.6.3"])
      s.add_dependency(%q<nokogiri>, ["~> 1.4.6"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<mocha>, ["~> 0.9.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_dependency(%q<simplecov>, ["~> 0.4.2"])
    end
  else
    s.add_dependency(%q<rest-client>, ["~> 1.6.3"])
    s.add_dependency(%q<nokogiri>, ["~> 1.4.6"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<mocha>, ["~> 0.9.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    s.add_dependency(%q<simplecov>, ["~> 0.4.2"])
  end
end

